# Generated by Django 5.1.4 on 2026-03-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="api_daily_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Custom daily AI generation limit. 0 = use system default (5)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(
                default=False, help_text="Block user from accessing the platform"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of logins"
            ),
        ),
    ]
