# Generated by Django 5.1.4 on 2026-03-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_user_monitoring_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_resume_creation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="resumes_created_today",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
