# Generated by Django 5.1.4 on 2026-03-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_emailotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, help_text="Last time the user made any request", null=True
            ),
        ),
    ]
