# Generated by Django 5.1.4 on 2026-03-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="resume_daily_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Custom daily resume creation limit. 0 = use system default (1)",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="api_daily_limit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Custom daily AI prompt limit. 0 = use system default (5)",
            ),
        ),
    ]
