# Generated by Django 5.1.4 on 2026-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_resume_daily_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="app_theme",
            field=models.CharField(
                choices=[
                    ("theme-ocean", "Ocean Mesh (Default)"),
                    ("theme-pink-3d", "Pink Horizon"),
                    ("theme-violet-3d", "Deep Violet X"),
                ],
                default="theme-ocean",
                help_text="Global application UI theme",
                max_length=50,
            ),
        ),
    ]
