# Generated by Django 5.1.4 on 2026-03-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_userprofile_app_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="app_theme",
            field=models.CharField(
                choices=[
                    ("system", "System Default"),
                    ("theme-ocean", "Ocean Mesh (Default)"),
                    ("theme-pink-3d", "Pink Horizon"),
                    ("theme-violet-3d", "Deep Violet X"),
                ],
                default="system",
                help_text="Global application UI theme",
                max_length=50,
            ),
        ),
    ]
