# Generated by Django 5.1.4 on 2026-03-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        choices=[
                            ("theme-ocean", "Ocean Mesh (Default)"),
                            ("theme-pink-3d", "Pink Horizon"),
                            ("theme-violet-3d", "Deep Violet X"),
                        ],
                        default="theme-ocean",
                        help_text="Default theme for logged-out users (e.g., landing page)",
                        max_length=50,
                    ),
                ),
                (
                    "enable_pink_theme",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to select the Pink Horizon theme",
                    ),
                ),
                (
                    "enable_violet_theme",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to select the Deep Violet X theme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
