# Nixpacks configuration for Railway

[phases.setup]
nixPkgs = ["...", "gcc", "libffi", "mupdf"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn core.wsgi --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
