# Generated by Django 5.1.4 on 2026-03-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIPromptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_type", models.CharField(max_length=50)),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                (
                    "model_used",
                    models.CharField(default="gemini-2.0-flash", max_length=100),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="My Resume", max_length=300)),
                (
                    "template_name",
                    models.CharField(
                        choices=[
                            ("modern_ats_clean", "Modern ATS Clean"),
                            ("minimal_academic", "Minimal Academic"),
                            ("corporate_executive", "Corporate Executive"),
                            ("creative_designer", "Creative Designer"),
                            ("technical_developer", "Technical Developer"),
                        ],
                        default="modern_ats_clean",
                        max_length=50,
                    ),
                ),
                ("latex_content", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("latex_content", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/pdf/"),
                ),
                (
                    "docx_file",
                    models.FileField(blank=True, null=True, upload_to="resumes/docx/"),
                ),
                ("change_note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="UploadedCV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploaded_cvs/")),
                ("original_filename", models.CharField(max_length=300)),
                ("extracted_data", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
