# Generated by Django 5.1.4 on 2026-03-03 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_alter_resume_template_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("model", "AI Model")], max_length=10
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
