# Generated by Django 5.1.4 on 2026-03-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0005_resumechatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="template_name",
            field=models.CharField(
                choices=[
                    ("modern_ats_clean", "Modern ATS Clean"),
                    ("minimal_academic", "Minimal Academic"),
                    ("corporate_executive", "Corporate Executive"),
                    ("creative_designer", "Creative Designer"),
                    ("technical_developer", "Technical Developer"),
                    ("startup_founder", "Startup Founder"),
                    ("data_scientist", "Data Scientist"),
                    ("marketing_pro", "Marketing Pro"),
                    ("legal_standard", "Legal Standard"),
                    ("medical_clinical", "Medical Clinical"),
                    ("ocean_blue_modern", "Ocean Blue Modern"),
                    ("pink_horizon_premium", "Pink Horizon Premium"),
                    ("violet_x_executive", "Violet X Executive"),
                    ("gold_luxury", "Gold Luxury"),
                ],
                default="modern_ats_clean",
                max_length=50,
            ),
        ),
    ]
